### ISSUE TITLE
Needs screenshot

### ISSUE THREAD

**Issue by peterjaap** [elgentos/Mailcheck#1]
![screenshot 2015-03-18 16 26 09](https://cloud.githubusercontent.com/assets/431360/6712189/909c1ca4-cd8b-11e4-8eac-9162ce4c3553.png)

**Comment by shirtsofholl** [comment]
ah. Yes. Maybe I can help too ... I will first test, then see/start from there

Silly question maybe: where can I find the options in system config?

**Comment by peterjaap** [comment]
See the readme;

> Configuration can be found under System > Configuration > Customer > Customer Configuration > Mailcheck.

:)
